Repository apache/logging-log4j-samples, pull requests merged in 2025-04, with the labels that each got.

#312 Typo fixes
  log4j-samples-asynclogger/README.md
  log4j-samples-asynclogger/src/main/java/org/apache/logging/log4j/samples/async/Log4J2AsyncLoggerExceptionExample.java
  log4j-spring-cloud-config-sample-application/README.md
Labels: documentation

#304 Remove daily samples build
  .github/workflows/build.yaml
Labels: github_actions

#313 Remove Apache Snapshots from release builds
  settings.gradle
Labels: enhancement

#310 Upgrade Gradle and Wrapper
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  log4j-samples-android/app/build.gradle
Labels: dependencies

#311 Remove `merge-dependabot` workflow
  .github/dependabot.yaml
  .github/workflows/build.yaml
  .github/workflows/merge-dependabot.yaml
Labels: enhancement
